FROM debian:12

# docker build -t gabo-db . -f Dockerfile-db
# docker run -dit -p 3306:3306 gabo-db

RUN apt update

COPY migracion/docker/dev/my.cnf /etc/my.cnf
RUN apt install -y mariadb-server

COPY migracion/docker/dev/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY migracion/docker/dev/entry-db.sh /usr/entry.sh
RUN chmod 755 /usr/entry.sh

COPY migracion/docker/dev/creacion_usuarios.sql /tmp/usuarios.sql
COPY migracion/docker/dev/respaldo.sql /tmp/respaldo.sql
COPY migracion/docker/dev/cambio_contr.sql /tmp/cambio_contr.sql

EXPOSE 3306
ENTRYPOINT ["bash", "/usr/entry.sh"]