CREATE TABLE IF NOT EXISTS `tb_59_mensaje_receptor` (
  `Consecutivo` INT NOT NULL,
  `Sucursal` INT NOT NULL,
  `ReceptorTipoIdentificacion` VARCHAR(20) NULL,
  `ReceptorIdentificacion` VARCHAR(50) NULL,
  `ReceptorCodigoPais` VARCHAR(4) NULL,
  `ConsecutivoHacienda` VARCHAR(30) NULL,
  `ConsecutivoFormateado` VARCHAR(11) NULL,
  `Situacion` VARCHAR(15) NULL,
  `CodigoSeguridad` VARCHAR(8) NULL,
  `TipoDocumento` VARCHAR(4) NULL,
  `Clave` VARCHAR(100) NULL,
  `EmisorIdentificacion` VARCHAR(50) NULL,
  `EmisorTipoIdentificacion` VARCHAR(20) NULL,
  `EmisorNombre` VARCHAR(200) NULL,
  `FechaEmision` VARCHAR(50) NULL,
  `TotalImpuestos` VARCHAR(20) NULL,
  `TotalComprobante` VARCHAR(20) NULL,
  `FechaEmisionComprobante` VARCHAR(50) NULL,
  `XMLSinFirmar` TEXT NULL,
  `XMLFirmado` TEXT NULL,
  `FechaRecibidoHacienda` TIMESTAMP NULL,
  `RespuestaHaciendaXML` TEXT NULL,
  `RespuestaHaciendaFecha` TIMESTAMP NULL,
  `RespuestaHaciendaEstado` VARCHAR(20) NULL,
  PRIMARY KEY (`Consecutivo`, `Sucursal`))
ENGINE = InnoDB